### ISSUE TITLE
Hall Sensors

### ISSUE THREAD

**Issue by mkierczak** [Damme/LandLord#10]
Hi!

I know it is a bit off-topic, but I am repairing an old Landroid WG794 and I found out that one of the Hall sensors on the lift sensor board is broken. This guy is in TO-92 enclosure and no part id is given. These boards are super difficult to get except Germany/Benelux but they do not ship to Scandinavia, where I live. Hall sensors are, on the other hand, rather easy to get. My question is whether you have figured out if these are binary NO/NC or linear-response Hall sensors? I thought of asking here before I take out oscilloscope and start testing. TIA. Martin

**Comment by Damme** [comment]
the cpu sees a binary value, I would guess they are binary but I have not looked if there are any comparators on the board for the sensors. I would test a simple one.

**Comment by mkierczak** [comment]
Thanx a lot! I'll try with simple binary.

**Comment by mkierczak** [comment]
For future reference. It seems that there are onboard comparators and I managed to get a replacement sensor. On the replacement, designation is "U57544" which according to (https://media.melexis.com/-/media/files/documents/datasheets/us5781-datasheet-melexis.pdf) corresponds to Melexis US5781 unipolar medium sensitivity Hall effect switch.
