### ISSUE TITLE
Unpacker not working ...

### ISSUE THREAD

**Issue by zombiefredrik** [Damme/LandLord#3]
Says this:
Unknown byte 0: 48
Unknown byte 1: 253
Unknown byte 2: 7
Unknown byte 3: 32
header end:     11467
Traceback (most recent call last):
  File "unpack_pck.py", line 74, in <module>
    nHeaders = b.count(int(13),4,datastart)
TypeError: Type int doesn't support the buffer API

**Comment by Damme** [comment]
Works in python 3, python 2 gives that error.. I don't know how to make that python code to work in python 2 :(

**Comment by AlexandreDecan** [comment]
The `bytearray.count` method was changed in Python 3.3 to accept as a first parameter not only a bytes-like object, but also an integer. See https://docs.python.org/3.5/library/stdtypes.html#bytearray.count for instance. 

As a workaround, you may simply convert `int(13)` (or `13`) to bytes:

``` python
brange = bytearray(range(3))
assert 1 == brange.count(bytearray([1]))
assert 0 == brange.count(bytearray([3]))
```

Tested in both Python 2.7 and 3.5.

**Comment by Damme** [comment]
I'm not following 100%, assert 0/1 ? how do I convert that into a result of the count found?
I'm certainly no python-guru ;)
nHeaders = ?assert?

**Comment by AlexandreDecan** [comment]
`assert` is a keyword that test the truth value of the given expression. In my example, this means that `brange.count(bytearray([1]))` returns `1` and that `brange.count(bytearray([3]))` returns `0`, which are the expected values ;-)

The key point is that you can replace your `b.count(int(13),4,datastart)` by `b.count(bytearray([13]),4,datastart)`. 

Notice that I didn't test the remaining of your code, so there could be other places where code does not work in Python 2. If you are interest, I may test the whole code later today.
